### ISSUE TITLE
[Bug] test_ray_serve is flaky

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#1058]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ci

### What happened + What you expected to happen

The following is copied from #1055.

## Experiments for 73b37b159c749377550775114b171a946734ece4

```sh
#!/bin/bash
for i in {1..25}
do
  RAY_IMAGE=rayproject/ray:2.1.0 python3 tests/compatibility-test.py RayFTTestCase 2>&1 | tee log_$i.txt
done
```
* Run `RayFTTestCase` 25 times on my devbox.
  * `test_detached_actor` never fails.
  * `test_ray_serve` fails 6 times.
      <details>
      <summary>test_ray_serve_1.py * 5</summary>
      
      ```
      ^[[2m^[[36m(ServeController pid=643)^[[0m INFO 2023-04-28 01:32:33,683 controller 643 http_state.py:132 - Starting HTTP proxy with name 'SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-c82ea22161ab30914ebd453cc3bd00e7e2088203b1506c26dc98116c' on node 'c82ea22161ab30914ebd453cc3bd00e7e2088203b1506c26dc98116c' listening on '127.0.0.1:8000'
      ^[[2m^[[36m(ServeController pid=643)^[[0m INFO 2023-04-28 01:32:33,716 controller 643 http_state.py:132 - Starting HTTP proxy with name 'SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-cc6e7b1793a1f6e801f67f310ef39428d54e15c3ca140fcc193795fd' on node 'cc6e7b1793a1f6e801f67f310ef39428d54e15c3ca140fcc193795fd' listening on '127.0.0.1:8000'
      ^[[2m^[[36m(ServeController pid=643)^[[0m INFO 2023-04-28 01:32:33,725 controller 643 http_state.py:132 - Starting HTTP proxy with name 'SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-438634dbcfb7ea6edd2cc3fef2feaf02ae2df4c6198e7a17a3155f72' on node '438634dbcfb7ea6edd2cc3fef2feaf02ae2df4c6198e7a17a3155f72' listening on '127.0.0.1:8000'
      ^[[2m^[[36m(HTTPProxyActor pid=700)^[[0m INFO:     Started server process [700]
      Traceback (most recent call last):
        File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serve/_private/api.py", line 241, in serve_start
          timeout=HTTP_PROXY_TIMEOUT,
        File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
          return getattr(ray, func.__name__)(*args, **kwargs)
        File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/api.py", line 42, in get
          return self.worker.get(vals, timeout=timeout)
        File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/worker.py", line 434, in get
          res = self._get(to_get, op_timeout)
        File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/worker.py", line 462, in _get
          raise err
      ray.exceptions.GetTimeoutError: Get timed out: some object(s) not ready.
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "samples/test_ray_serve_1.py", line 15, in <module>
          handle = serve.run(MyModelDeployment.bind(msg="Hello world!"))
        File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serve/api.py", line 483, in run
          http_options={"host": host, "port": port, "location": "EveryNode"},
        File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serve/_private/api.py", line 245, in serve_start
          f"HTTP proxies not available after {HTTP_PROXY_TIMEOUT}s."
      TimeoutError: HTTP proxies not available after 60s.
      command terminated with exit code 1
      ```
      </details>
      <details>
      <summary>test_ray_serve_2.py * 1 </summary>
      
      ```
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/home/ray/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
          timeout=timeout
        File "/home/ray/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 786, in urlopen
          method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
        File "/home/ray/anaconda3/lib/python3.7/site-packages/urllib3/util/retry.py", line 592, in increment
          raise MaxRetryError(_pool, url, error or ResponseError(cause))
      urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcabbf355d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "samples/test_ray_serve_2.py", line 23, in <module>
          retry_with_timeout(send_req, 180)
        File "samples/test_ray_serve_2.py", line 14, in retry_with_timeout
          raise err
        File "samples/test_ray_serve_2.py", line 9, in retry_with_timeout
          return func()
        File "samples/test_ray_serve_2.py", line 17, in send_req
          response = requests.get('http://127.0.0.1:8000', timeout=10)
        File "/home/ray/anaconda3/lib/python3.7/site-packages/requests/api.py", line 76, in get
          return request('get', url, params=params, **kwargs)
        File "/home/ray/anaconda3/lib/python3.7/site-packages/requests/api.py", line 61, in request
          return session.request(method=method, url=url, **kwargs)
        File "/home/ray/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
          resp = self.send(prep, **send_kwargs)
        File "/home/ray/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
          r = adapter.send(request, **kwargs)
        File "/home/ray/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
          raise ConnectionError(e, request=request)
      requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcabbf355d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
      command terminated with exit code 1
      ```
      </details>

The `test_ray_serve_1.py`'s error message is from the [link](https://sourcegraph.com/github.com/ray-project/ray@0d59be7f27454200c9a2c153ad14b0ad00d541e5/-/blob/python/ray/serve/_private/api.py?L169-L209). The reason seems to be failing to get HTTPProxy actors which is similar to my observation above "(Bug? Ray 2.1.0) In some cases, HTTPProxy will not be created on the head Pod after the cluster recovers from a failure.". I will file an issue later, but the check seems to be legacy code.

### Reproduction script

See the section "Experiments for https://github.com/ray-project/kuberay/commit/73b37b159c749377550775114b171a946734ece4" in #1055 for more details.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by sihanwang41** [comment]
issue is on 2.5 which is fixed in 2.6. (https://github.com/ray-project/ray/pull/36461)

**Comment by sihanwang41** [comment]
synced offline. @kevin85421 will verify the 2.6 version, and make ci to run the test only on the 2.6.

**Comment by kevin85421** [comment]
I ran `test_ray_serve` with `rayproject/ray:2.6.0` 20 times, resulting in 19 passes and 1 failure. The failure is not related to this issue (HTTPProxyActor). I will open a PR to ensure `test_ray_serve` is only triggered by versions later than Ray 2.6.0.

```sh
#!/bin/bash

for i in {1..20}
do
    echo "Running iteration $i"
    RAY_IMAGE=rayproject/ray:2.6.0 python3 tests/compatibility-test.py RayFTTestCase.test_ray_serve 2>&1 | tee logs/log_$i
done
```
