### ISSUE TITLE
[Bug] Crash observed in ci test

### ISSUE THREAD

**Issue by wilsonwang371** [ray-project/kuberay#124]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ci

### What happened + What you expected to happen

we observed a crash in the test while running CI.

https://github.com/ray-project/kuberay/runs/4848463209

```
•E0118 03:24:24.694308   10306 runtime.go:78] Observed a panic: runtime.boundsError{x:1, y:1, signed:true, code:0x0} (runtime error: index out of range [1] with length 1)
goroutine 1262 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x17f75c0, 0xc0009b3ba0)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.14/pkg/util/runtime/runtime.go:74 +0xa6
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.14/pkg/util/runtime/runtime.go:48 +0x89
panic(0x17f75c0, 0xc0009b3ba0)
	/opt/hostedtoolcache/go/1.15.15/x64/src/runtime/panic.go:969 +0x1b9
github.com/ray-project/kuberay/ray-operator/controllers.(*RayClusterReconciler).reconcilePods(0xc000998500, 0xc0004a9680, 0x0, 0x0)
	/home/runner/work/kuberay/kuberay/ray-operator/controllers/raycluster_controller.go:169 +0x2ddb
github.com/ray-project/kuberay/ray-operator/controllers.(*RayClusterReconciler).Reconcile(0xc000998500, 0x1aebf00, 0xc000a1dd40, 0xc000c2d530, 0x7, 0xc0009028c0, 0x11, 0xc000a1dd40, 0x40c0ff, 0xc000032000, ...)
	/home/runner/work/kuberay/kuberay/ray-operator/controllers/raycluster_controller.go:92 +0x40e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000220280, 0x1aebe40, 0xc000998800, 0x1768ca0, 0xc000819760)
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:263 +0x317
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000220280, 0x1aebe40, 0xc000998800, 0x0)
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:235 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1(0x1aebe40, 0xc000998800)
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:198 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.14/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00002af50)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.14/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000a33f50, 0x1ab2660, 0xc000d275f0, 0xc000998801, 0xc0009c0060)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.14/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00002af50, 0x3b9aca00, 0x0, 0x1, 0xc0009c0060)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.14/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x1aebe40, 0xc000998800, 0xc0004d8aa0, 0x3b9aca00, 0x0, 0x1)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.14/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x1aebe40, 0xc000998800, 0xc0004d8aa0, 0x3b9aca00)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.14/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:195 +0x4e7
panic: runtime error: index out of range [1] with length 1 [recovered]
	panic: runtime error: index out of range [1] with length 1

goroutine 1262 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.14/pkg/util/runtime/runtime.go:55 +0x10c
panic(0x17f75c0, 0xc0009b3ba0)
	/opt/hostedtoolcache/go/1.15.15/x64/src/runtime/panic.go:969 +0x1b9
github.com/ray-project/kuberay/ray-operator/controllers.(*RayClusterReconciler).reconcilePods(0xc000998500, 0xc0004a9680, 0x0, 0x0)
	/home/runner/work/kuberay/kuberay/ray-operator/controllers/raycluster_controller.go:169 +0x2ddb
github.com/ray-project/kuberay/ray-operator/controllers.(*RayClusterReconciler).Reconcile(0xc000998500, 0x1aebf00, 0xc000a1dd40, 0xc000c2d530, 0x7, 0xc0009028c0, 0x11, 0xc000a1dd40, 0x40c0ff, 0xc000032000, ...)
	/home/runner/work/kuberay/kuberay/ray-operator/controllers/raycluster_controller.go:92 +0x40e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000220280, 0x1aebe40, 0xc000998800, 0x1768ca0, 0xc000819760)
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:263 +0x317
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000220280, 0x1aebe40, 0xc000998800, 0x0)
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:235 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1(0x1aebe40, 0xc000998800)
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:198 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.14/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00002af50)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.14/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000a33f50, 0x1ab2660, 0xc000d275f0, 0xc000998801, 0xc0009c0060)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.14/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00002af50, 0x3b9aca00, 0x0, 0x1, 0xc0009c0060)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.14/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x1aebe40, 0xc000998800, 0xc0004d8aa0, 0x3b9aca00, 0x0, 0x1)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.14/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x1aebe40, 0xc000998800, 0xc0004d8aa0, 0x3b9aca00)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.14/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:195 +0x4e7
FAIL	github.com/ray-project/kuberay/ray-operator/controllers	6.632s
ok  	github.com/ray-project/kuberay/ray-operator/controllers/common	0.008s	coverage: 73.1% of statements
ok  	github.com/ray-project/kuberay/ray-operator/controllers/utils	0.007s	coverage: 31.4% of statements
?   	github.com/ray-project/kuberay/ray-operator/pkg/client/clientset/versioned	[no test files]
?   	github.com/ray-project/kuberay/ray-operator/pkg/client/clientset/versioned/fake	[no test files]
?   	github.com/ray-project/kuberay/ray-operator/pkg/client/clientset/versioned/scheme	[no test files]
?   	github.com/ray-project/kuberay/ray-operator/pkg/client/clientset/versioned/typed/raycluster/v1alpha1	[no test files]
?   	github.com/ray-project/kuberay/ray-operator/pkg/client/clientset/versioned/typed/raycluster/v1alpha1/fake	[no test files]
?   	github.com/ray-project/kuberay/ray-operator/pkg/client/informers/externalversions	[no test files]
?   	github.com/ray-project/kuberay/ray-operator/pkg/client/informers/externalversions/internalinterfaces	[no test files]
?   	github.com/ray-project/kuberay/ray-operator/pkg/client/informers/externalversions/raycluster	[no test files]
?   	github.com/ray-project/kuberay/ray-operator/pkg/client/informers/externalversions/raycluster/v1alpha1	[no test files]
?   	github.com/ray-project/kuberay/ray-operator/pkg/client/listers/raycluster/v1alpha1	[no test files]
FAIL
make: *** [Makefile:56: test] Error 1
```

### Reproduction script

not able to reproduce this.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by wilsonwang371** [comment]
I assume there is a bug at here?

https://github.com/ray-project/kuberay/blob/71a238a990754c2d7b91339b2f91f3822a6ebee7/ray-operator/controllers/raycluster_controller.go#L172

**Comment by Jeffwan** [comment]
Thanks @wilsonwang371  for fixing the issue!
