### ISSUE TITLE
[Bug] RayService with GCS FT HA issue

### ISSUE THREAD

**Issue by YQ-Wang** [ray-project/kuberay#1463]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

Others

### What happened + What you expected to happen

I set up a KubeRay RayService using an external Redis for fault tolerance. The RayService hosted a web service, and I used "mobilenet" as a sample. However, when I removed the head pod, the following issues arose: even though the worker pod remains active, the service named "svc/rayservice-mobilenet-serve-svc" can't process requests after the head's deletion.

I expect the svc to keep serving the request properly after the head is down.

```
...
{"prediction": ["n02099601", "golden_retriever", 0.786209762096405]}
{"prediction": ["n02099601", "golden_retriever", 0.786209762096405]}
Traceback (most recent call last):
  File "/Users/yqw/.pyenv/versions/3.9.15/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/yqw/.pyenv/versions/3.9.15/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/yqw/.pyenv/versions/3.9.15/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/yqw/.pyenv/versions/3.9.15/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/Users/yqw/.pyenv/versions/3.9.15/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/Users/yqw/.pyenv/versions/3.9.15/lib/python3.9/http/client.py", line 289, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yqw/.pyenv/versions/3.9.15/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/Users/yqw/.pyenv/versions/3.9.15/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/yqw/.pyenv/versions/3.9.15/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/yqw/.pyenv/versions/3.9.15/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/Users/yqw/.pyenv/versions/3.9.15/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/yqw/.pyenv/versions/3.9.15/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/yqw/.pyenv/versions/3.9.15/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/yqw/.pyenv/versions/3.9.15/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/Users/yqw/.pyenv/versions/3.9.15/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/Users/yqw/.pyenv/versions/3.9.15/lib/python3.9/http/client.py", line 289, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yqw/Desktop/ray-playground/mobilenet_req.py", line 12, in <module>
    response = requests.post(url, files=files)
  File "/Users/yqw/.pyenv/versions/3.9.15/lib/python3.9/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/Users/yqw/.pyenv/versions/3.9.15/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/yqw/.pyenv/versions/3.9.15/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/yqw/.pyenv/versions/3.9.15/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Users/yqw/.pyenv/versions/3.9.15/lib/python3.9/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

### Reproduction script

All the code can be found here: https://github.com/YQ-Wang/ray-playground

Step 1: Install KubeRay Operator
`helm install kuberay-operator kuberay/kuberay-operator --version <0.6.0 or 1.0.0-rc.0>`

Step 2: Install Ray Service
The yaml file has the Ray head integrated with an external Redis
`kubectl --context kind-kind apply -f ray-service.mobilenet-ft.yaml`

Step 3:
`kubectl port-forward svc/rayservice-mobilenet-serve-svc 8000`

Step 4: Run the client code
`python mobilenet_req.py`

Step 5: Delete the head pod
`kubectl --context kind-kind delete pod <head pod>`

Step 6: Monitor the client output
You will find the client side raise exception

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
I can reproduce this issue. This may be a Ray Serve bug or misconfiguration. cc @edoakes @akshay-anyscale would you mind taking a look? Thanks!

* `kubectl describe svc rayservice-mobilenet-serve-svc`: There are 1 head node and 1 worker node in the RayCluster. However, the service only has 1 endpoint from Ray head. 
  <img width="847" alt="Screen Shot 2023-10-19 at 1 38 33 PM" src="https://github.com/ray-project/kuberay/assets/20109646/05fc7c01-e8d3-4350-9567-2a13e46f0e8e">

* The Ray head has a HTTPProxyActor.
  <img width="1440" alt="Screen Shot 2023-10-19 at 1 40 57 PM" src="https://github.com/ray-project/kuberay/assets/20109646/e169cf36-f2e7-45e0-9813-090b2b28256c">

* However, there is no HTTPProxyActor in the worker node.
   <img width="1439" alt="Screen Shot 2023-10-19 at 1 42 07 PM" src="https://github.com/ray-project/kuberay/assets/20109646/d273a165-bea5-47e6-8725-206754252664">

* The value of ProxyLocation is "EveryNode". Hence, every node should have HTTPProxyActor.
  <img width="1440" alt="Screen Shot 2023-10-19 at 1 44 34 PM" src="https://github.com/ray-project/kuberay/assets/20109646/aadd53c3-78e2-4ba8-8029-8f9ada63134c">

**Comment by akshay-anyscale** [comment]
@kevin85421 nodes/pods without a replica do not have httpproxy. Looks like that is what is going on here

**Comment by kevin85421** [comment]
cc @shrekris-anyscale

**Comment by kevin85421** [comment]
> nodes/pods without a replica do not have httpproxy.

I'm not sure whether this is correct. I've conducted benchmarks where I created two Ray nodes. Only the worker node had 16 replicas, while the head node didn't have any. If I remember correctly, the head node has an HTTPProxyActor. @shrekris-anyscale will check the details. Thanks!

**Comment by akshay-anyscale** [comment]
The head node always has a proxy actor. @GeneDer can you confirm the behavior?

**Comment by GeneDer** [comment]
Yes, just remembered there are some behavior change. TLDR is like Akshay mentioned in the terminal state there will only be proxy on head node + active worker nodes (defined as nodes that has replicas). 

Previously we will deploy proxy to all nodes (given the proxy location is everywhere). If the node has no replicas, then we will mark that proxy to be in the DRAINING state and failing the health check. This will help upscaling and downscaling to work correctly without affecting ongoing requests and allow enough time for a node to process requests. Proxy will be remained on the inactive cluster, but unreachable. 

The current behavior is that we won't even start a proxy on an inactive worker node. During each update loop, we will first check which nodes are active, then we put the proxy on the active node + head node. And during downscaling the same logic applies when a worker node turns inactive, it's proxy will be marked as DRAINING state to allow enough time to process ongoing requests, and then gets shutdown. So in the terminal states only head node + the active worker nodes will have proxies running

**Comment by kevin85421** [comment]
Thanks, @akshay-anyscale and @GeneDer! 

> in the terminal state there will only be proxy on head node + active worker nodes (defined as nodes that has replicas).

Could you point me to the function I should read? Thanks!

**Comment by GeneDer** [comment]
The code that decides which proxy to start and stop is https://github.com/ray-project/ray/blob/master/python/ray/serve/_private/proxy_state.py#L672-L673

**Comment by GeneDer** [comment]
You might also be interested in https://github.com/ray-project/ray/blob/master/python/ray/serve/_private/cluster_node_info_cache.py#L17 as it determines the active nodes
