### ISSUE TITLE
[Bug] GKE autopilot cluster - Have you run 'ray start' on this node?

### ISSUE THREAD

**Issue by hammad26** [ray-project/kuberay#1563]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

Hi
I am following a simple [tutorial](https://github.com/ray-project/kuberay/blob/master/ray-operator/config/samples/ray-cluster.complete.yaml) (ray-cluster.complete.yaml) to generate my ray cluster on GKE autopilot. Only difference from the tutorial is that I added GPU while creating ray cluster. As soon as my worker is started, I am getting following messages in the logs:

```
[2023-10-24 03:59:58,924 W 8 8] global_state_accessor.cc:401: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?

[2023-10-24 03:59:59,926 W 8 8] global_state_accessor.cc:401: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?
```

Then after one minute, its showing traceback:
```
Traceback (most recent call last):
  File "/home/ray/anaconda3/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/scripts/scripts.py", line 2490, in main
    return cli()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ray/anaconda3/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/cli_logger.py", line 856, in wrapper
    return f(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/scripts/scripts.py", line 920, in start
    node = ray._private.node.Node(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/node.py", line 156, in __init__
    self._init_gcs_client()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/node.py", line 729, in _init_gcs_client
    raise RuntimeError(
RuntimeError: Failed to connect to GCS.
```

In GKE autopilot cluster, nodes are fully managed by Google. How can I fix this issue? 

### Reproduction script

```
apiVersion: ray.io/v1
kind: RayCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
    # A unique identifier for the head node and workers of this cluster.
  name: raycluster-complete
  # namespace: converse
spec:
  rayVersion: '2.7.0'
  # Ray head pod configuration
  headGroupSpec:
    serviceType: ClusterIP
    # The `rayStartParams` are used to configure the `ray start` command.
    # See https://github.com/ray-project/kuberay/blob/master/docs/guidance/rayStartParams.md for the default settings of `rayStartParams` in KubeRay.
    # See https://docs.ray.io/en/latest/cluster/cli.html#ray-start for all available options in `rayStartParams`.
    rayStartParams:
      dashboard-host: '0.0.0.0'
    # pod template
    template:
      metadata:
        labels: {}
      spec:
        containers:
        - name: ray-head
          image: rayproject/ray:2.7.0
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 6379
            name: gcs
          - containerPort: 8265
            name: dashboard
          - containerPort: 10001
            name: client
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","ray stop"]
          volumeMounts:
            - mountPath: /tmp/ray
              name: ray-logs
          resources:
            limits:
              cpu: "1"
              memory: "2G"
            requests:
              cpu: "1"
              memory: "2G"
        volumes:
          - name: ray-logs
            emptyDir: {}
  workerGroupSpecs:
  # the pod replicas in this group typed worker
  - replicas: 1
    minReplicas: 1
    maxReplicas: 1
    groupName: small-group
    rayStartParams: {}
    #pod template
    template:
      spec:
        nodeSelector:
          cloud.google.com/gke-accelerator: nvidia-tesla-t4
        containers:
        - name: ray-worker
          image: rayproject/ray:2.7.0
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","ray stop"]
          # use volumeMounts.Optional.
          # Refer to https://kubernetes.io/docs/concepts/storage/volumes/
          volumeMounts:
            - mountPath: /tmp/ray
              name: ray-logs
          resources:
            limits:
              cpu: "3"
              memory: "20G"
              nvidia.com/gpu: 2
            requests:
              cpu: "3"
              # For production use-cases, we recommend allocating at least 8Gb memory for each Ray container.
              memory: "20G"
              nvidia.com/gpu: 2
        # use volumes
        # Refer to https://kubernetes.io/docs/concepts/storage/volumes/
        volumes:
          - name: ray-logs
            emptyDir: {}
######################status#################################

```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
I think it has already been solved by https://github.com/ray-project/kuberay/pull/1470. You can try the latest release candidate v1.0.0-rc.1.

**Comment by kevin85421** [comment]
Close this issue. Feel free to reopen it if it does not address your issue.

**Comment by hammad26** [comment]
Yes, I am already following that thread and using the latest release `1.0.0-rc.1` in my experiments. Surprisingly, didn't facing any issues today. Must be something at GKE autopilot cluster then.
