### ISSUE TITLE
[Bug] [API Server] JobSubmission API returns 502 on jobs that do not exist

### ISSUE THREAD

**Issue by smit-kiri** [ray-project/kuberay#1714]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

apiserver

### What happened + What you expected to happen

On the latest nightly, sending a request to `namespaces/{ns}/jobsubmissions/{name}/{sid}` returns a 502 for an SID that does not exist. The API Server Pod restarts, and I see this error:

```
I1205 21:37:46.492423       1 interceptor.go:14] /proto.RayJobSubmissionService/GetJobDetails handler starting
{"level":"info","v":0,"logger":"jobsubmissionservice","message":"RayJobSubmissionService get service"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x16f23fb]

goroutine 482 [running]:
github.com/ray-project/kuberay/apiserver/pkg/server.convertNodeInfo(0x0)
        /workspace/apiserver/pkg/server/ray_job_submission_service_server.go:190 +0x7b
github.com/ray-project/kuberay/apiserver/pkg/server.(*RayJobSubmissionServiceServer).GetJobDetails(0xc0004683f0, {0x1d44d38, 0xc0007d09c0}, 0xc0000b5a40)
        /workspace/apiserver/pkg/server/ray_job_submission_service_server.go:99 +0x186
github.com/ray-project/kuberay/proto/go_client._RayJobSubmissionService_GetJobDetails_Handler.func1({0x1d44d38, 0xc0007d09c0}, {0x196e8a0?, 0xc0000b5a40})
        /workspace/proto/go_client/job_submission_grpc.pb.go:184 +0x78
github.com/ray-project/kuberay/apiserver/pkg/interceptor.ApiServerInterceptor({0x1d44d38, 0xc0007d09c0}, {0x196e8a0, 0xc0000b5a40}, 0xc0000f87c0, 0xc00019c9c0)
        /workspace/apiserver/pkg/interceptor/interceptor.go:15 +0x137
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x1d44d38?, 0xc0007d09c0?}, {0x196e8a0?, 0xc0000b5a40?})
        /opt/app-root/src/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1({0x1d44d38, 0xc0007d09c0}, {0x196e8a0, 0xc0000b5a40}, 0x18d0140?, 0xc0000f8820)
        /opt/app-root/src/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107 +0x87
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x1d44d38?, 0xc0007d09c0?}, {0x196e8a0?, 0xc0000b5a40?})
        /opt/app-root/src/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1({0x1d44d38, 0xc0007d09c0}, {0x196e8a0, 0xc0000b5a40}, 0xc000179a00?, 0x187ba60?)
        /opt/app-root/src/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34 +0xbe
github.com/ray-project/kuberay/proto/go_client._RayJobSubmissionService_GetJobDetails_Handler({0x196e520?, 0xc0004683f0}, {0x1d44d38, 0xc0007d09c0}, 0xc000518900, 0xc000468450)
        /workspace/proto/go_client/job_submission_grpc.pb.go:186 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000214000, {0x1d44d38, 0xc0007d0900}, {0x1d4b138, 0xc0005bb520}, 0xc00011c6c0, 0xc0004695c0, 0x34a60d8, 0x0)
        /opt/app-root/src/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:1343 +0xe49
google.golang.org/grpc.(*Server).handleStream(0xc000214000, {0x1d4b138, 0xc0005bb520}, 0xc00011c6c0)
        /opt/app-root/src/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:1737 +0xca6
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        /opt/app-root/src/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:986 +0x8c
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/app-root/src/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:997 +0x15c

```

Ideally it should return a 404.

### Reproduction script

Send a request to `namespaces/{ns}/jobsubmissions/{name}/{sid}` with an `sid` that does not exist.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
cc @blublinsky @z103cb @astefanutti @tedhtchang
