### ISSUE TITLE
[Bug] worker group cannot be removed from RayCluster

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/kuberay#1739]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

Adding a new `WorkerGroup` to a RayCluster works fine, you can see the pod come up.  But when you remove that workergroup, the pod never gets terminated, and the head pod autoscaler starts to go into a crash loop.

I'm not 100% sure if this behavior is supported, but if so it's a bug.

### Reproduction script

```

# Modify the below YAML file to have `replicas: 1` so that we can watch a worker pod come up.  Apply the YAML.
kubectl apply -f ray-operator/config/samples/ray-cluster.autoscaler.yaml

watch kubectl get pod # wait until head and worker pods come up

# Now add a new entry to `WorkerGroupSpec`, copying the first entry, but changing the name to `small-group-2`.

kubectl apply -f ray-operator/config/samples/ray-cluster.autoscaler.yaml

watch kubectl get pod # wait for the second worker pod to come up

# Now remove the new entry to `WorkerGroupSpec` that we just added.

kubectl apply -f ray-operator/config/samples/ray-cluster.autoscaler.yaml
```

Now the second worker pod will never terminate, and the head pod autoscaler container will crashloop with 

```python-traceback

Traceback (most recent call last):
  File "/home/ray/anaconda3/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/scripts/scripts.py", line 2498, in main
    return cli()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ray/anaconda3/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/scripts/scripts.py", line 2234, in kuberay_autoscaler
    run_kuberay_autoscaler(cluster_name, cluster_namespace)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/kuberay/run_autoscaler.py", line 54, in run_kuberay_autoscaler
    Monitor(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py", line 586, in run
    self._run()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py", line 391, in _run
    self.autoscaler.update()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/autoscaler.py", line 383, in update
    raise e
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/autoscaler.py", line 376, in update
    self._update()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/autoscaler.py", line 464, in _update
    self.provider.post_process()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/batching_node_provider.py", line 150, in post_process
    self.submit_scale_request(self.scale_request)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/kuberay/node_provider.py", line 282, in submit_scale_request
    patch_payload = self._scale_request_to_patch_payload(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/kuberay/node_provider.py", line 363, in _scale_request_to_patch_payload
    group_index = _worker_group_index(raycluster, node_type)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/kuberay/node_provider.py", line 185, in _worker_group_index
    return group_names.index(group_name)
ValueError: 'small-group-2' is not in list

```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
After discussing this offline, we decided not to support the removal of a worker group from RayCluster for the following reasons:

* The implementation is complex.
* There have been no user requests for this feature.
* We lack a method to drain the Ray nodes before deleting the Pods, which makes it highly likely that Ray Pods with running tasks or actors will be deleted.

**Comment by architkulkarni** [comment]
Yup. We should still reject such an update with a clear error message. I'll leave the issue up to track this.

**Comment by omkar619-dev** [comment]
I'd like to pick this up, but I want to confirm the intended approach first since the answer isn't obvious.

Confirmed still reproducible on master: \
econcilePods\ only iterates \instance.Spec.WorkerGroupSpecs\ (raycluster_controller.go#L1069), so pods of a removed group are never visited by any code path.

For the rejection itself, \RayClusterWebhook.ValidateUpdate\ already receives the old object and discards it, so the check is small there — but webhooks are gated behind \ENABLE_WEBHOOKS\ and the Helm chart doesn't ship webhook templates, so a webhook-only fix wouldn't protect a default install. The alternative is a CEL transition rule, matching the existing \self == oldSelf\ immutability markers on \managedBy\ / \gcsFaultToleranceOptions.backend\. Two caveats here though: it must be a field-level marker on \RayCluster.Spec\ only (removal is legitimate in \RayService.spec.rayClusterConfig\, which correctly triggers a new cluster), and the subset check is O(n^2) over a \workerGroupSpecs\ list with no \MaxItems\, so it may hit the CEL cost limit unless we bound the list.

Proposal: CEL rule to reject the update, plus a status condition/event in the controller so clusters already in this state get a clear signal instead of a silent autoscaler crash-loop. Does that match what you had in mind, or is the webhook the preferred home? Also happy to revisit whether removal should be supported, now that node draining exists.

**Comment by nataliekung** [comment]
Following up with current `master` evidence at `d77dadd`: [`reconcilePods`](https://github.com/ray-project/kuberay/blob/d77dadd43948b80faabd2c99a0f7665ef535b90c/ray-operator/controllers/ray/raycluster_controller.go#L1068-L1081) only iterates worker groups still present in `instance.Spec.WorkerGroupSpecs`, so Pods from a removed group are never listed or reconciled. [`ValidateUpdate`](https://github.com/ray-project/kuberay/blob/d77dadd43948b80faabd2c99a0f7665ef535b90c/ray-operator/pkg/webhooks/v1/raycluster_webhook.go#L37-L40) also still ignores the old object.

A webhook-only fix would not protect default Helm installs: the manager registers webhooks only when [`ENABLE_WEBHOOKS=true`](https://github.com/ray-project/kuberay/blob/d77dadd43948b80faabd2c99a0f7665ef535b90c/ray-operator/main.go#L344-L350), while the `kuberay-operator` chart does not set that flag or install webhook configuration/certificate templates by default.

Could a maintainer choose the intended enforcement point: admission webhook validation, a CRD CEL transition rule, or a controller fail-fast warning Event/status Condition? Once the ownership is clear, I am happy to send a focused PR.

**Comment by omkar619-dev** [comment]
Thanks for picking this up. Some concerns on scope and API compatibility.

On direction: #1739 was scoped to rejecting the update with a clear error  @architkulkarni 's follow-up), after  @kevin85421 's decision not to support removal at all — the blocker there was the lack of a way to drain Ray nodes before Pod deletion, which \`workerGroupDeletion\` doesn't address. Commit 2 adds a permanent CRD field plus a requestID protocol to *permit* removal, which reopens that decision and seems like it needs its own API discussion rather than riding on a P2 bug fix. I think Commit 1 on its own looks much closer to what the issue asked for.

Three compatibility concerns regardless of the direction:

1. \`+listType=map\` on \`workerGroupSpecs\` changes server-side-apply semantics from atomic replacement to key-based merge for every existing user (Helm, ArgoCD, Kueue). That's a behavior change on a GA API and probably the biggest risk in this PR.
2. \`+kubebuilder:validation:MaxItems=100\` narrows a previously unbounded field; existing CRs above the bound would fail on their next update.
3. The combined rule is now ~700 characters. As I noted on #1739, the subset check is O(n^2) and the reason to bound the list at all is the CEL cost estimator — worth confirming, the estimated cost stays under the per-expression limit on the oldest supported Kubernetes version, since a rejected CRD fails at install time.

Would it be worth splitting this: commit 1's single rule as the minimal fix for #1739, and the explicit-deletion API as a separate proposal?

**Comment by nataliekung** [comment]
Opened #5142 as a separate design proposal for *safe* worker group removal — draining each group's Ray nodes before Pod deletion, as an explicit opt-in that sits on top of the reject-by-default work in #5132. It targets the original blocker from this issue (kevin85421, https://github.com/ray-project/kuberay/issues/1739#issuecomment-1856778086): no way to drain Ray nodes before deleting their Pods. Keeping it out of the P2 bug fix here, per the scope discussion. Feedback welcome on the design.

**Comment by omkar619-dev** [comment]
Thanks for the split — this addresses all three of my concerns. The minimal rule matches what #1739 asked for, and documenting MaxItems/MaxLength as load-bearing for installability is the right call i believe.

**Comment by omkar619-dev** [comment]
I verified this revision (9f01cf8) against a live apiserver rather than envtest — k3s v1.35.5, CRD installed via server-side apply, no operator running, since the rule is enforced entirely by the apiserver.

| case | result |
| --- | --- |
| CRD install (static CEL cost) | accepted |
| head-only cluster, spec update | accepted |
| cluster stored with \`workerGroupSpecs: []\`, spec update | accepted |
| remove one group of three | rejected, intended message |
| remove all groups | rejected, intended message |
| modify replicas on an existing group | accepted |
| append a group | accepted |
| reorder groups only | accepted |
| removal via \`RayService.spec.rayClusterConfig\` | accepted |
| removal via the v1alpha1 endpoint | rejected, intended message |

Two notes. The \`has()\` guards behave correctly on both the absent-field and stored-empty-list paths — under the earlier unguarded form these produced \`no such key: workerGroupSpecs evaluating rule\`, and that error is gone. And the installed CRD reports \`v1alpha1 served=true, storage=false\`, so mirroring the rule onto it was necessary; the mirror fires.

This is unrelated to this PR, but worth noting for anyone reproducing manually: the RayCluster CRD can't be installed with client-side \`kubectl apply\` — it exceeds the 256KB last-applied-configuration annotation limit. \`--server-side\` is required. Pre-existing on master."

**Comment by nataliekung** [comment]
Thanks for taking the time to verify this against a live apiserver — really appreciate it, especially confirming the `has()` guards on both the absent-field and stored-empty-list paths and that the v1alpha1 mirror fires. Good call on the `--server-side` requirement for CRD install; that one's pre-existing on master (the CRD exceeds the 256KB client-side last-applied annotation limit), so I'll keep it out of this PR's scope. I think this is ready for maintainer review whenever someone has bandwidth.

**Comment by machichima** [comment]
@omkar619-dev @nataliekung 
Regarding https://github.com/ray-project/kuberay/issues/5142, as I commented under that issue, we will come back to it once there's more users requesting it.

I think https://github.com/ray-project/kuberay/pull/5132 may be something we could add, will have a look

**Comment by omkar619-dev** [comment]
Thanks @machichima. One thing worth triaging alongside #5132: the CEL rule rejects new removals, but clusters already in this state get no signal — the orphaned Pods just sit there unreconciled while the head autoscaler crash-loops, which is the symptom in the original report. #5143 covers that half (status condition plus a one-shot warning Event, gated behind the existing RayClusterStatusConditions gate) and hasn't had any review yet.

Happy to run #5143 against a live apiserver the same way I did #5132 if that's useful.

**Comment by nataliekung** [comment]
Thanks @machichima — that split makes sense to me, and I'm happy to defer #5142. Waiting for more user demand before taking on the draining orchestration is completely reasonable; I'll keep the proposal open as a marker for when that signal shows up.

On the two halves that stand on their own for #1739:

**#5132 (reject-by-default).** This is the minimal fail-closed guard the original thread asked for — it just rejects removing a worker group via a CRD CEL transition rule, with no new API surface and no controller changes. @omkar619-dev independently verified the current revision (`9f01cf8`) against a live apiserver (k3s v1.35.5, CRD applied server-side, no operator running), covering 10 cases including head-only clusters, the stored-empty-list path, the v1alpha1 mirror, and RayService — all passing. So the risk surface is small and well-exercised. Thanks for offering to take a look.

**#5143 (signal for clusters already in the bad state).** This is the other half @omkar619-dev flagged: the CEL rule stops *new* removals, but clusters that are already in this state get no signal today — the orphaned Pods sit unreconciled while the head autoscaler crash-loops, which is the original symptom here. As a data point on "real users hitting this": on a shared cluster we ran into exactly this failure mode — after the head crash-looped through repeated restarts, a worker group was left orphaned, its Pods were never reconciled, and a leaked placement group kept holding its GPUs idle until we manually released the placement group and deleted the orphaned workers. #5143 adds a status condition plus a one-shot warning Event (gated behind the existing RayClusterStatusConditions gate) so this state is at least observable instead of silent. It's a small, read-only-to-the-user diagnostic and doesn't depend on the draining work in #5142.

@omkar619-dev's offer to run #5143 against a live apiserver the same way would be great. Thanks again for triaging this.
