### ISSUE TITLE
[Bug] KubeRay site shows 404 error

### ISSUE THREAD

**Issue by Jeffwan** [ray-project/kuberay#228]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

Others

### What happened + What you expected to happen

![image](https://user-images.githubusercontent.com/4739316/162691642-acdaf033-da71-4969-8609-645f4237965f.png)

Looks like gh-pages branch is created successfully and CI job also works fine. However, we see above 404 issues.

![image](https://user-images.githubusercontent.com/4739316/162691748-8461fdc5-a90e-421a-bb8b-479fddca3dfa.png)

![image](https://user-images.githubusercontent.com/4739316/162691886-213b137f-d6eb-4210-b720-becdde48c8a7.png)

### Reproduction script

CI job or other setting may not incorrect?

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by Jeffwan** [comment]
https://www.it3.be/2020/08/14/using-mkdocs-with-gh-pages/
Thanks for this post. This is really a pitfall. Looks like our setting is empty and I change to `gh-pages` and `/docs` to render the site. 

In order to trigger the rebuild, I manually run this command but notice it try to push to `origin`. In my env, `origin` points to my personal fork. I don't want to manually refresh the page and let's wait for new coming commits to retrigger the site built.


```
➜  kuberay git:(doc_site) ✗ docker run --rm -it -v ${PWD}:/docs squidfunk/mkdocs-material gh-deploy
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: /docs/site
INFO     -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
              - release/README.md
WARNING  -  Documentation file 'components/operator.md' contains a link to 'components/media/overview.png' which is not found in the documentation files.
WARNING  -  Documentation file 'components/operator.md' contains a link to 'components/media/create-ray-cluster.gif' which is not found in the documentation files.
WARNING  -  Documentation file 'components/operator.md' contains a link to 'components/media/update-ray-cluster.gif' which is not found in the documentation files.
WARNING  -  Documentation file 'components/operator.md' contains a link to 'components/msft-operator/ray-operator/config/samples/config-map-ray-code.yaml' which is not found in the documentation files.
WARNING  -  Documentation file 'components/operator.md' contains a link to 'components/media/logs-ray-cluster.gif' which is not found in the documentation files.
WARNING  -  Documentation file 'components/operator.md' contains a link to 'components/config/samples/ray-cluster.mini.yaml' which is not found in the documentation files.
WARNING  -  Documentation file 'components/operator.md' contains a link to 'components/config/samples/ray-cluster.heterogeneous.yaml' which is not found in the documentation files.
WARNING  -  Documentation file 'components/operator.md' contains a link to 'components/config/samples/ray-cluster.complete.yaml' which is not found in the documentation files.
WARNING  -  Documentation file 'release/README.md' contains a link to '../CHANGELOG.md' which is not found in the documentation files.
INFO     -  Documentation built in 1.63 seconds
WARNING  -  Version check skipped: No version specified in previous deployment.
INFO     -  Copying '/docs/site' to 'gh-pages' branch and pushing to GitHub.
The authenticity of host 'github.com (20.205.243.166)' can't be established.
ECDSA key fingerprint is SHA256:p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com,20.205.243.166' (ECDSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/__main__.py", line 209, in gh_deploy_command
    gh_deploy.gh_deploy(cfg, message=message, force=force, ignore_version=ignore_version, shell=shell)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/gh_deploy.py", line 108, in gh_deploy
    ghp_import.ghp_import(
  File "/usr/local/lib/python3.9/site-packages/ghp_import.py", line 263, in ghp_import
    git.check_call('push', opts['remote'], opts['branch'])
  File "/usr/local/lib/python3.9/site-packages/ghp_import.py", line 121, in check_call
    sp.check_call(['git'] + list(args), **kwargs)
  File "/usr/local/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'push', 'origin', 'gh-pages']' returned non-zero exit status 128.
```

**Comment by Jeffwan** [comment]
![image](https://user-images.githubusercontent.com/4739316/162771015-0e05aec2-efa5-450c-8296-8b54fae62cd8.png)
CI job failed due to setting

**Comment by Jeffwan** [comment]
![image](https://user-images.githubusercontent.com/4739316/164123967-49e72a49-ac0a-4a7d-81ab-e65f72bf31aa.png)

**Comment by Jeffwan** [comment]
![image](https://user-images.githubusercontent.com/4739316/164182622-5cb39b82-17ca-4e9a-8fd5-fc2c44f1c7ec.png)
https://github.com/ray-project/kuberay/runs/6091282074?check_suite_focus=true

This is fixed by using a different action.
