### ISSUE TITLE
[Bug] Ray Job submit fails when GCS is enabled

### ISSUE THREAD

**Issue by XBeg9** [ray-project/kuberay#2676]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

export RAY_ADDRESS=http://172.27.0.143:8265 && ray job submit --verbose --working-dir job -- python script.py

```sh
RuntimeError: Request failed with status code 500: No available agent to submit job, please try again later..
```

### Reproduction script

```python
# script.py
import ray

@ray.remote
def hello_world():
    return "hello world"

# Automatically connect to the running Ray cluster.
ray.init()
print(ray.get(hello_world.remote()))
```

GCS is enabled on cluster (redis)

export RAY_ADDRESS=http://172.27.0.143:8265 && ray job submit --verbose --working-dir job -- python script.py

### Anything else

Same cluster, but without GCS works as expected job is submitted.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by prd-tuong-nguyen** [comment]
same problem!

**Comment by rmanak** [comment]
same problem for me!

**Comment by kevin85421** [comment]
@hongbo-miao would you mind sharing logs with me?

1. dashboard log
2. dashboard agent logs
3. raylet logs

**Comment by hongbo-miao** [comment]
Thanks @kevin85421 ! I will share when it happens again next time.

**Comment by kevin85421** [comment]
You can also set `RAY_BACKEND_LOG_LEVEL=debug` so that the C++ debug logs will be printed.

**Comment by hongbo-miao** [comment]
Hi @kevin85421 it failed again, here is the logs. Thanks! (Note I haven't got chance to enable `RAY_BACKEND_LOG_LEVEL=debug` this time)

[logs.zip](https://github.com/user-attachments/files/20042624/logs.zip)

**Comment by kevin85421** [comment]
# Logs

* dashboard.log
  ```
  2025-05-03 01:37:02,468	ERROR job_head.py:267 -- Failed to get head node agent, retrying in 0.5 seconds...
  Traceback (most recent call last):
    File "/home/ray/anaconda3/lib/python3.12/site-packages/ray/dashboard/modules/job/job_head.py", line 265, in _get_head_node_agent
      return await self._get_head_node_agent_once()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/ray/anaconda3/lib/python3.12/site-packages/ray/dashboard/modules/job/job_head.py", line 252, in _get_head_node_agent_once
      ip, http_port, grpc_port = await self._fetch_agent_info(head_node_id)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/ray/anaconda3/lib/python3.12/site-packages/ray/dashboard/modules/job/job_head.py", line 306, in _fetch_agent_info
      raise KeyError(
  KeyError: 'Agent info not found in internal kv for node NodeID(8e0070ecae20a61b3e1adcf6889f23639c908d003f471db9d7964477)'
  ```

* gcs_server.out
  ```
  [2025-05-03 01:36:39,127 I 75 75] (gcs_server) gcs_node_manager.cc:88: Registering node info, address = 172.31.150.32, node name = 172.31.150.32 node_id=b8c6a97e2a6c5c1e2f63600e22e9739f7672e9c6c1cd4b94ef2e8486
  [2025-05-03 01:36:39,128 I 75 75] (gcs_server) gcs_node_manager.cc:382: Removing node, node name = 172.31.178.3, death reason = UNEXPECTED_TERMINATION, death message = health check failed due to missing too many heartbeats node_id=8e0070ecae20a61b3e1adcf6889f23639c908d003f471db9d7964477
  [2025-05-03 01:36:39,128 W 75 75] (gcs_server) gcs_node_manager.cc:411: The node with node id: 8e0070ecae20a61b3e1adcf6889f23639c908d003f471db9d7964477 and address: 172.31.178.3 and node name: 172.31.178.3 has been marked dead because the detector has missed too many heartbeats from it. This can happen when a 	(1) raylet crashes unexpectedly (OOM, etc.) 
  	(2) raylet has lagging heartbeats due to slow network or busy workload.
  [2025-05-03 01:36:39,128 I 75 75] (gcs_server) gcs_placement_group_manager.cc:800: Node failed, rescheduling the placement groups on the dead node. node_id=8e0070ecae20a61b3e1adcf6889f23639c908d003f471db9d7964477
  [2025-05-03 01:36:39,128 I 75 75] (gcs_server) gcs_actor_manager.cc:1282: Node failed, reconstructing actors. node_id=8e0070ecae20a61b3e1adcf6889f23639c908d003f471db9d7964477
  [2025-05-03 01:36:39,128 I 75 75] (gcs_server) gcs_job_manager.cc:467: Node failed, mark all jobs from this node as finished node_id=8e0070ecae20a61b3e1adcf6889f23639c908d003f471db9d7964477
  ```

* monitor.log
  ```
  type=headgroup, cloud_instance_id=, ray_id=): allocated unmanaged worker cloud instance from ray node: 8e0070ecae20a61b3e1adcf6889f23639c908d003f471db9d7964477
  ...
  type=headgroup, cloud_instance_id=horizon-ray-cluster-head-c448x, ray_id=): ray node 8e0070ecae20a61b3e1adcf6889f23639c908d003f471db9d7964477 is DEAD
  ```

# Summary

* Ray job submission tries to get head node agent from `NodeID(8e0070ecae20a61b3e1adcf6889f23639c908d003f471db9d7964477)`
* However, the node is an dead Ray head node.

**Comment by hongbo-miao** [comment]
Thanks @kevin85421 how can we avoid this issue? As the Ray head node is still up when the issue happens, and we can still access the UI. My workaround way is restart head node pod right now.

**Comment by kevin85421** [comment]
Ray requires some fixes so that Ray dashboard can get the information of the new head node. The current workaround is to disable GCS FT. 

We currently don't have a lot of tests for GCS FT with everything other than Ray Serve.

https://docs.ray.io/en/latest/cluster/kubernetes/user-guides/kuberay-gcs-ft.html#kuberay-gcs-ft

![Image](https://github.com/user-attachments/assets/634fb41f-7987-4ec2-8dc5-c61314e7effc)

**Comment by kevin85421** [comment]
https://github.com/ray-project/ray/pull/54267

**Comment by pulnarayana1** [comment]
Hi @kevin85421 Thank you for fixing this.
When can we expect the new release to be cut, that would include this change ?

**Comment by kevin85421** [comment]
https://github.com/ray-project/ray/pull/54267#discussion_r2217136415

It is hard to reproduce on the new releases. If it's urgent, you don't need to wait for the new release.
