### ISSUE TITLE
[Bug] Ray client timeout errors using v0.3.0

### ISSUE THREAD

**Issue by richardsliu** [ray-project/kuberay#507]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

Using kuberay v0.3.0 (cluster version 1.21.13-gke.900), I am always seeing ray client timeout errors:

```
/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/worker.py:258: UserWarning: Ray Client connection timed out. Ensure that the Ray Client port on the head node is reachable from your local machine. See https://docs.ray.io/en/latest/cluster/ray-client.html#step-2-check-ports for more information.
  "Ray Client connection timed out. Ensure that "
Traceback (most recent call last):
  File "job_example.py", line 54, in <module>
    ray.init("ray://example-cluster-ray-head-svc:10001")
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 887, in init
    return builder.connect()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/client_builder.py", line 164, in connect
    ray_init_kwargs=self._remote_init_kwargs,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client_connect.py", line 45, in connect
    ray_init_kwargs=ray_init_kwargs,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/__init__.py", line 243, in connect
    conn = self.get_context().connect(*args, **kw_args)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/__init__.py", line 91, in connect
    connection_retries=connection_retries,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/worker.py", line 143, in __init__
    self._connect_channel()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/worker.py", line 264, in _connect_channel
    raise ConnectionError("ray client connection timeout")
ConnectionError: ray client connection timeout
```

### Reproduction script

This is my job yaml:

```
apiVersion: batch/v1
kind: Job
metadata:
  namespace: [name]
  name: ray-test-job
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: Never
      containers:
        - name: ray
          image: rayproject/ray:latest 
          imagePullPolicy: Always
          command: [ "/bin/bash", "-c", "--" ]
          args:
            - "wget https://raw.githubusercontent.com/ray-project/ray/master/doc/kubernetes/example_scripts/job_example.py &&
              sed -i 's/example-cluster-ray-head/example-cluster-ray-head-svc/g' job_example.py && python job_example.py"
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by Jeffwan** [comment]
@richardsliu Can you share the cluster pods & service status? Seem client can not connect to Ray service

1. make sure the service name is correct 
2. Make sure there're endpoints for the service
3. Make sure head is up and running. Let's check /tmp/ray/xxx to see whether the main process reports any issue.

**Comment by richardsliu** [comment]
This is the service:

```
Name:              example-cluster-ray-head-svc
Namespace:         ricliu
Labels:            app.kubernetes.io/created-by=kuberay-operator
                   app.kubernetes.io/name=kuberay
                   ray.io/cluster=example-cluster-ray
                   ray.io/identifier=example-cluster-ray-head
                   ray.io/node-type=head
Annotations:       cloud.google.com/neg: {"ingress":true}
Selector:          app.kubernetes.io/created-by=kuberay-operator,app.kubernetes.io/name=kuberay,ray.io/cluster=example-cluster-ray,ray.io/identifier=example-cluster-ray-head,ray.io/node-type=head
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                10.8.32.145
IPs:               10.8.32.145
Port:              dashboard  8265/TCP
TargetPort:        8265/TCP
Endpoints:         <none>
Port:              metrics  8080/TCP
TargetPort:        8080/TCP
Endpoints:         <none>
Port:              serve  8000/TCP
TargetPort:        8000/TCP
Endpoints:         <none>
Port:              client  10001/TCP
TargetPort:        10001/TCP
Endpoints:         <none>
Port:              redis  6379/TCP
TargetPort:        6379/TCP
Endpoints:         <none>
Session Affinity:  None
Events:            <none>
```

The cluster was deployed using the example cluster config here: https://github.com/ray-project/kuberay/blob/master/helm-chart/ray-cluster/values.yaml

I didn't see any obvious errors in the ray head, but the workers seem to have a lot of errors:

```
2022-08-25 17:13:05,401 WARNING utils.py:1243 -- Unable to connect to GCS at example-cluster-ray-head-svc:6379. Check that (1) Ray GCS with matching version started successfully at the specified address, and (2) there is no firewall setting preventing access.
2022-08-25 17:09:31,183 INFO scripts.py:870 -- Local node IP: 10.16.2.5
Traceback (most recent call last):
  File "/home/ray/anaconda3/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/scripts/scripts.py", line 2339, in main
    return cli()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/cli_logger.py", line 852, in wrapper
    return f(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/scripts/scripts.py", line 873, in start
    ray_params, head=False, shutdown_at_exit=block, spawn_reaper=block
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/node.py", line 189, in __init__
    num_retries=NUM_REDIS_GET_RETRIES,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/utils.py", line 1259, in internal_kv_get_with_retry
    f"Could not read '{key.decode()}' from GCS. Did GCS start successfully?"
RuntimeError: Could not read 'session_name' from GCS. Did GCS start successfully?
```

**Comment by richardsliu** [comment]
Repro steps:

```
$ git clone https://github.com/ray-project/kuberay
$ git checkout v0.3.0
$ cd kuberay/helm-chart/
$ helm -n ricliu install example-cluster ./ray-cluster/ --create-namespace
```

**Comment by richardsliu** [comment]
Tried it again on clusters from https://github.com/ray-project/kuberay/tree/master/ray-operator/config/samples and it doesn't seem to repro, so it is likely a problem with the helm installation charts. 

@Jeffwan
