### ISSUE TITLE
[Bug] Deleting and recreating RayCluster can lead to error to reconcile.

### ISSUE THREAD

**Issue by tgaddair** [ray-project/kuberay#66]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

Because there is not yet rolling update support, it's often necessary to stop and restart the RayCluster in quick succession to push updates. It seems in some cases this can lead to an error where there are temporarily two head node pods for the cluster at once:

```
2021-10-15T03:39:42.599Z	INFO	raycluster-controller	Reconciling RayCluster	{"cluster name": "cluster-3"}
2021-10-15T03:39:42.599Z	INFO	RayCluster-Controller	checkSvcName 	{"svc name amended": "cluster-3-service"}
2021-10-15T03:39:42.606Z	INFO	raycluster-controller	Pod service already exist,no need to create
2021-10-15T03:39:42.606Z	INFO	raycluster-controller	checkPods 	{"more than 1 head pod found for cluster": "cluster-3"}
E1015 03:39:42.606835       1 runtime.go:73] Observed a panic: runtime.boundsError{x:1, y:1, signed:true, code:0x0} (runtime error: index out of range [1] with length 1)
goroutine 291 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1344420, 0xc00099e840)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/runtime/runtime.go:69 +0x7b
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/runtime/runtime.go:51 +0x89
panic(0x1344420, 0xc00099e840)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
ray-operator/controllers.(*RayClusterReconciler).checkPods(0xc00073e600, 0xc0000d5c00, 0xc0005409f0, 0x22, 0x0, 0x1a)
	/workspace/controllers/raycluster_controller.go:128 +0x2b15
ray-operator/controllers.(*RayClusterReconciler).Reconcile(0xc00073e600, 0xc000513630, 0x9, 0xc00050d220, 0x1a, 0x5f3c0599, 0xc0000b33b0, 0xc00052e048, 0xc00052e000)
	/workspace/controllers/raycluster_controller.go:94 +0x475
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00029e000, 0x12d3ce0, 0xc00000c080, 0xc00070a500)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.3.0/pkg/internal/controller/controller.go:216 +0x166
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00029e000, 0xc0004b6f00)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.3.0/pkg/internal/controller/controller.go:192 +0xb0
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc00029e000)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.3.0/pkg/internal/controller/controller.go:171 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00062b020)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00062b020, 0x3b9aca00, 0x0, 0x1488001, 0xc0000b8180)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:153 +0x105
k8s.io/apimachinery/pkg/util/wait.Until(0xc00062b020, 0x3b9aca00, 0xc0000b8180)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.3.0/pkg/internal/controller/controller.go:157 +0x331
panic: runtime error: index out of range [1] with length 1 [recovered]
	panic: runtime error: index out of range [1] with length 1

goroutine 291 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/runtime/runtime.go:58 +0x10c
panic(0x1344420, 0xc00099e840)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
ray-operator/controllers.(*RayClusterReconciler).checkPods(0xc00073e600, 0xc0000d5c00, 0xc0005409f0, 0x22, 0x0, 0x1a)
	/workspace/controllers/raycluster_controller.go:128 +0x2b15
ray-operator/controllers.(*RayClusterReconciler).Reconcile(0xc00073e600, 0xc000513630, 0x9, 0xc00050d220, 0x1a, 0x5f3c0599, 0xc0000b33b0, 0xc00052e048, 0xc00052e000)
	/workspace/controllers/raycluster_controller.go:94 +0x475
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00029e000, 0x12d3ce0, 0xc00000c080, 0xc00070a500)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.3.0/pkg/internal/controller/controller.go:216 +0x166
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00029e000, 0xc0004b6f00)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.3.0/pkg/internal/controller/controller.go:192 +0xb0
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc00029e000)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.3.0/pkg/internal/controller/controller.go:171 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00062b020)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00062b020, 0x3b9aca00, 0x0, 0x1488001, 0xc0000b8180)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:153 +0x105
k8s.io/apimachinery/pkg/util/wait.Until(0xc00062b020, 0x3b9aca00, 0xc0000b8180)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.3.0/pkg/internal/controller/controller.go:157 +0x331
```

### Reproduction script

Seems to be a race condition, as it doesn't always happen. But the general approach was to delete on cluster then recreate it with the same name.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by tgaddair** [comment]
Thanks! Sounds like it may be fixed by updating to latest, which is great.

**Comment by feilengcui008** [comment]
@Jeffwan I think it's because the OwnerReference field of service and pod are not set properly，so the log info "Pod service already exist,no need to create"， when delete a ray cluster crd，those should be deleted automatically.

**Comment by Jeffwan** [comment]
Looks ownerReference setting is fine. I run a test to uninstall operator pod first and then delete cluster, pods and services are cleaned up which means cascading deletion works fine


Service
```
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-10-16T05:10:22Z"
  labels:
    ray.io/cluster: raycluster-mini
    ray.io/identifier: raycluster-mini-head
    ray.io/node-type: head
  name: raycluster-mini-head-svc
  namespace: default
  ownerReferences:
  - apiVersion: ray.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: RayCluster
    name: raycluster-mini
    uid: 845ab41f-8e4f-4bd0-9c44-32e7945b6810
  resourceVersion: "12084534"
```

Pods
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-10-16T05:10:22Z"
  generateName: raycluster-mini-head-
  labels:
    ray.io/cluster: raycluster-mini
    ray.io/group: headgroup
    ray.io/identifier: raycluster-mini-head
    ray.io/is-ray-node: "yes"
    ray.io/node-type: head
  name: raycluster-mini-head-6tdkb
  namespace: default
  ownerReferences:
  - apiVersion: ray.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: RayCluster
    name: raycluster-mini
    uid: 845ab41f-8e4f-4bd0-9c44-32e7945b6810
  resourceVersion: "12084674"

```

**Comment by DmitriGekhtman** [comment]
This has been solved.
