### ISSUE TITLE
[Bug] Failed to submit job due to invalid character error

### ISSUE THREAD

**Issue by pingsutw** [ray-project/kuberay#897]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

Failed to submit the ray job due to below error.
```bash
2023-02-06T16:47:48.194Z	ERROR	controllers.RayJob	failed to submit job	{"error": "invalid character 'T' looking for beginning of value"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227
```
```bash
  Runtime Env:  ewogICAgInBpcCI6IFsKICAgICAgICAicmVxdWVzdHM9PTIuMjYuMCIsCiAgICAgICAgInBlbmR1bHVtPT0yLjEuMiIKICAgIF0sCiAgICAiZW52X3ZhcnMiOiB7ImNvdW50ZXJfbmFtZSI6ICJ0ZXN0X2NvdW50ZXIifQp9Cg==
Status:
  Dashboard URL:          rayjob-sample-1-raycluster-qlcqb-head-svc.flyte.svc.cluster.local:8265
  Job Deployment Status:  FailedJobDeploy
  Job Id:                 rayjob-sample-1-2lxvh
  Ray Cluster Name:       rayjob-sample-1-raycluster-qlcqb
  Ray Cluster Status:
    Available Worker Replicas:  1
    Desired Worker Replicas:    1
    Endpoints:
      Client:        10001
      Dashboard:     8265
      Gcs - Server:  6379
      Serve:         8000
    Head:
      Pod IP:             10.244.0.76
      Service IP:         10.96.208.86
    Last Update Time:     2023-02-06T16:47:40Z
    Max Worker Replicas:  5
    Min Worker Replicas:  1
    State:                ready
Events:
  Type    Reason   Age    From               Message
  ----    ------   ----   ----               -------
  Normal  Created  3m41s  rayjob-controller  Created cluster rayjob-sample-1-raycluster-qlcqb
```

Note: This error doesn't happen all the time. This most likely happens when you run two Ray jobs at the same time.

### Reproduction script

```bash
kubectl apply -f sample/ray_v1alpha1_rayjob.yaml
# update the name of rayjob to rayjob-sample-1
kubectl apply -f sample/ray_v1alpha1_rayjob.yaml
```

### Anything else

Install Kuberay from master branch

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
The error is reported by `json.Unmarshal`. 

https://github.com/ray-project/kuberay/blob/af8fb0c833a850cd925bed8c59321d7b4bde6514/ray-operator/controllers/ray/utils/dashboard_httpclient.go#L378

The root cause is that `body` is not a valid JSON object. When it reports `"invalid character 'T' looking for beginning of value"`, the value of `body` is (note: the first character is "T"):

```
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/job/job_head.py", line 292, in submit_job
    resp = await job_agent_client.submit_job_internal(submit_request)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/job/job_head.py", line 82, in submit_job_internal
    await self._raise_error(resp)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/job/job_head.py", line 68, in _raise_error
    raise RuntimeError(f"Request failed with status code {status}: {error_text}.")
RuntimeError: Request failed with status code 500: Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/job/job_agent.py", line 52, in submit_job
    entrypoint_resources=submit_request.entrypoint_resources,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/job/job_manager.py", line 747, in submit_job
    raise RuntimeError(f"Job {submission_id} already exists.")
RuntimeError: Job rayjob-sample-xvkv6 already exists.
```

Apparently, the "Traceback" message is not a valid JSON. Btw, you can use `string(body)` to see the Traceback message. @architkulkarni can open a PR to surface the real question ("Traceback") rather than "invalid character 'T' looking for beginning of value".

**Comment by kevin85421** [comment]
#1000 relieves this issue.
