### ISSUE TITLE
[Bug] Ray 2.3.0 cannot connect to Redis

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#927]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

```
Enable usage stats collection? This prompt will auto-proceed in 10 seconds to avoid blocking cluster startup. Confirm [Y/n]: Y
Usage stats collection is enabled. To disable this, add `--disable-usage-stats` to the command that starts the cluster, or run the following command: `ray disable-usage-stats` before starting the cluster. See https://docs.ray.io/en/master/cluster/usage-stats.html for more details.

Local node IP: 10.244.0.10
Traceback (most recent call last):
  File "/home/ray/anaconda3/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/scripts/scripts.py", line 2422, in main
    return cli()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/cli_logger.py", line 852, in wrapper
    return f(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/scripts/scripts.py", line 738, in start
    ray_params, head=True, shutdown_at_exit=block, spawn_reaper=block
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/node.py", line 287, in __init__
    self.start_head_processes()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/node.py", line 1121, in start_head_processes
    self._write_cluster_info_to_kv()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/node.py", line 1070, in _write_cluster_info_to_kv
    ray_usage_lib.put_cluster_metadata(self.get_gcs_client())
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/usage/usage_lib.py", line 525, in put_cluster_metadata
    namespace=ray_constants.KV_NAMESPACE_CLUSTER,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/gcs_utils.py", line 198, in wrapper
    return f(self, *args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/gcs_utils.py", line 317, in internal_kv_put
    reply = self._kv_stub.InternalKVPut(req, timeout=timeout)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:10.244.0.10:6379: Failed to connect to remote host: Connection refused"
        debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv4:10.244.0.10:6379: Failed to connect to remote host: Connection refused {grpc_status:14, created_time:"2023-02-23T16:09:22.480155658-08:00"}"
>
```

### Reproduction script

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: redis-config
  labels:
    app: redis
data:
  redis.conf: |-
    dir /data
    port 6379
    bind 0.0.0.0
    appendonly yes
    protected-mode no
    requirepass 5241590000000000
    pidfile /data/redis-6379.pid
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:5.0.8
          command:
            - "sh"
            - "-c"
            - "redis-server /usr/local/etc/redis/redis.conf"
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: config
              mountPath: /usr/local/etc/redis/redis.conf
              subPath: redis.conf
      volumes:
        - name: config
          configMap:
            name: redis-config
---
apiVersion: v1
kind: Pod
metadata:
  name: ray
spec:
  containers:
  - image: rayproject/ray:2.3.0
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: ray
  restartPolicy: Always
```

The script above is to deploy a Ray Pod and Redis Pod without KubeRay. 

```sh
kubectl apply -f $ABOVE_SCRIPT

# Log in to the Ray Pod
kubectl exec -it ray --bash

# Try to connect to Redis in the Pod
RAY_REDIS_ADDRESS=redis:6379 ray start --head
```

  <details>
  <summary>Succeed with `rayproject/ray:2.2.0` Docker image (Expected)</summary>
  <img width="1436" alt="Screen Shot 2023-02-23 at 4 05 37 PM" src="https://user-images.githubusercontent.com/20109646/221059368-1c4311f4-3795-44be-9491-799f6405d172.png">
  </details>
  <details>
  <summary>Fail with `rayproject/ray:2.3.0` Docker image (Unexpected)</summary>
<img width="1440" alt="Screen Shot 2023-02-23 at 4 09 33 PM" src="https://user-images.githubusercontent.com/20109646/221059828-d2396708-736d-45ea-801d-a101f9d71f42.png">
  </details>

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
This bug needs to be fixed by the Ray community to make sure Ray FT works well.

**Comment by kevin85421** [comment]
Also, opened an issue in the Ray repo https://github.com/ray-project/ray/issues/32794.
